### ISSUE TITLE
Nested/repeated fields

### ISSUE THREAD

**Issue by arturi** [enokidotsite/enoki#10]
Hi! Cool project, got me very excited. I’ve been working on similar ideas here: https://github.com/arturi/tent. 

Now it’s just a markdown editor with live preview and drag and drop file support, but initially I was playing with an idea of having a configurable field editor: https://github.com/arturi/tent/blob/master/screenshot.jpg.

Have you considered nested/repeated fields? For example: I want to list my favorite places in Tokyo, where `Tokyo` would be a page, and `place` would be a field with `name`, `details`, `picture` and `link` as subfields, and I could add as many of these `places` as I wanted to.

**Comment by jondashkyle** [comment]
Hey @arturi! Thanks for hanging in there; Enoki has been undergoing some extensive development in the meantime, this feature will be added soon!
