### ISSUE TITLE
Rename enoki.json

### ISSUE THREAD

**Issue by jondashkyle** [enokidotsite/enoki#12]
There are a few other apps appearing which share a common structure with Enoki. They have similar configuration options, however Enoki uses `enoki.json` for these options. For these applications to work nicely with each other, this should probably be renamed to something tool-agnostic.

@kodedninja’s [orkl](https://github.com/kodedninja/orkl) project is a good example of such a tool, and uses `config.json`, which makes sense. I wonder if we should use something self-describing, such as `site.json`? Consider how `npm` uses `package.json` for anything related to the package/module. That level of specificity allows for other `json` configuration files to be understandable.

**Comment by kodedninja** [comment]
My only concern about ```site.json``` is that not all ```dat://``` projects are Beaker based (sites) and in the future they might use this configuration too. 

I know sites dominate and will dominate in the future too, but more Electron based apps or else may come.

**Comment by pfrazee** [comment]
I can't say for sure, but I agree I might consider a less generic name unless you're certain it's going to be a very reusable schema.

**Comment by jondashkyle** [comment]
Two other ideas:

- Enoki is focusing on the `dat://` ecosystem. Maybe this could be defined in `dat.json`? 
- The `site` configuration could be a key in `package.json`, and we expect that to always be placed in the root directory of the archive, unlike now, which exists at `/source/package.json`

Zooming out a little further, @pfrazee, I wonder how we can configure applications in the `dat://` ecosystem which share options, such as “Where does the content exist?”. There is already a bit of awkward overlap for this with Enoki. It stores the site title in a separate place than where the archive title is defined. This overlaps with the question of data portability, too.

**Comment by pfrazee** [comment]
@jondashkyle yeah I'm interested. I'm already thinking heavily about adding a generic `links` attribute to the dat.json, that will work like `<link>` elements (ie have `href` and `rel` and `title`). What all do you need to store?

**Comment by jondashkyle** [comment]
@pfrazee The most important are `title` and `content`, with `content` being a path. Because `dat.json`. For an application like Enoki there are more granular settings which I wouldn’t think another application (even in the same space) would need access to.

The more I think about this, the more it seems to relate to the broader data portability project. Perhaps `dat.json` accepts a `config` key, which points to wherever your app configuration json is located, and it is formatted in json-lz, although that all seems pretty involved.

**Comment by pfrazee** [comment]
Yeah I agree, it fits in that conversation. We just need to keep gathering requirements and eventually the solutions should become obvious enough, I think

**Comment by jondashkyle** [comment]
`enoki.json` is now `site.json`: https://github.com/enokidotsite/enoki/pull/17
