### ISSUE TITLE
Random Enoki dev experiences/thoughts

### ISSUE THREAD

**Issue by joehand** [enokidotsite/enoki#13]
I finished [updating my old Enoki site to the new Enoki](https://github.com/joehand/jhand-space/pull/1) and had a few notes, comments, etc.:

## Development Quirks

I never really figured out how to smoothly do development b/c of a few overlapping issues:

* How the `bundles/content.json` gets created in the panel is very magical. Took me a bit to figure out that I had to open my site in the panel to get that file created.
  * It'd be cool for development to have something I can run outside the panel to create that file.
* Confusing how to develop where I was changing content and JS stuff at the same time. It'd be good to specify how to use the panel during theme development. 
  * I started by developing as I'd normally do (using a `npm start` and a local server or something). But that didn't work unless I manually updated content.json. 
  * I tried to move to doing development in Beaker but got confused by the workspace thing (think they're aware of the issue there).

## Feature/Doc Needs

* ~How blueprints works? I have a [links section](https://github.com/joehand/jhand-space/blob/0881103fbf32a62f8812e03c47d891fd032499bd/content/index.txt#L8-L24) on my homepage and want to add that to the panel. I could probably figure it out but was feeling lazy atm. I'm sure you're aware of this need. =)~ Just found this in the panel guides section
* View random sites in Enoki! I want to link to the non-editable Enoki panel for my site (e.g. `dat://enoki.panel/?site=dat://<random-key>`, to show people how it works. I think this will showcase how easy it is to move data between custom viewers.
* Deployment tips (to deploy with github pages or similar and dat). Main thing I think will be hard is the single page app stuff. The fallback page part in dat.json was also a bit magic.

**Comment by joehand** [comment]
I didn't look at the guides until now. So apologies if you covered some of this there. It'd be good to surface those a bit in the github readmes.

**Comment by jondashkyle** [comment]
@joehand Such good feedback, appreciated! I think you’re on point with all of this.

- Yeah, the `content.json` is a bit of a hack at the moment. I created a small script which outputs the `content.json` via an npm script. Bundling that into the Enoki module makes a lot of sense.
- You’re right about the Beaker dev experience with workspaces. They are working on it, which is good news! Finding an elegant way to transition between developing in Beaker and an HTTP server is high on the list. Perhaps the way to do this for now is to simply watch the `/content` for changes and write `content.json` when using an Enoki transform? Hmm.
- Yes! Have thought about a way of passing a `dat://` url into the Panel. Clicking save if you aren’t an owner could perhaps prompt you to fork.
- The “creating your first enoki site” guide goes over deployment a bit, but I agree there could be a dedicated guide for that.

Thanks again for taking the time to give it a look. Quite rough around the edges, so this type of feedback helps a lot.
