### ISSUE TITLE
Running into a problem when updating my Enoki site, and then hosting it over HTTP via the Dat CLI

### ISSUE THREAD

**Issue by stephenkistner** [enokidotsite/enoki#14]
Not sure if this is a workflow problem, or an issue with Enoki, as I can't really diagnose it beyond the error I'm getting. 

Though it seems to be a problem with how `content.json` is syncing between local files and my server. (even when running `build` and then publishing the changes, it seems like the new `content.json` file isn't being grabbed on the HTTP site)

This is what I'm getting in the devtools:

![screen shot 2018-04-13 at 11 46 56 am](https://user-images.githubusercontent.com/15961273/38744823-d3a22b3e-3f10-11e8-92eb-1ac634d7c23e.png)

The site will render hardcoded elements, but anything relying on Enoki content isn't being rendered.

My DNS shortname updates and works fine on dat://, its just HTTP where changes aren't propagating.

So maybe its a problem with the `build` script? Or maybe a caching issue?

Let me know if you need any other info from me!

**Comment by jondashkyle** [comment]
Hey! Currently, `content.json` is only generated when saving from the Enoki Panel. I’m working now to create an Enoki `cli` which can be added to the `build` script, effectively doing what you want! Have run into the same issue, and appreciate the issue! As a temp fix you can do immediately, here is an example of a script which does just that:

https://github.com/peer-to-peer-web/p2p-web-site/blob/berlin/source/lib/build.js

You could then put in your build script something like this:

```
"build": "node ./source/lib/build.js && browserify etc…"
```

**Comment by jondashkyle** [comment]
Good news! A CLI has been added in the most recent release. You can generate the `content.json` fallback simply by running `enok content` on your site’s root directory. More about that here: https://github.com/enokidotsite/enoki/pull/17

Going to go ahead and close this one.
