### ISSUE TITLE
Feature Request: Ability to pass in a Hyperdrive instance

### ISSUE THREAD

**Issue by austinfrey** [enokidotsite/enoki#19]
### Use Case
Use a browser based `hyperdrive`/`indexeddb` instance as the filesystem for `enoki` content. I'd still like to serve my site over standard HTTP to regular browsers but not rely on the `content.json` file to provide my content. This would also allow me to write to the drive from regular browsers as well. If I could pass a custom `hyperdrive` instance, I could do something like the following.

```javascript
const hyperdrive = require('hyperdrive')
const rai = require('random-access-idb')('db')
const Enoki = require('enoki')

const archive = hyperdrive(rai)
const enoki = new Enoki(archive, defaults)
...
```
Honestly not sure how feasible this would be, but it seems like it could work and allow for some more flexibility when wanting to use `enoki` in environments like standard browsers/PWA's and `cordova` apps where `fs` access is not available and neither would the DatArchive API's.

Thoughts?

**Comment by austinfrey** [comment]
I stumbled across @RangerMauve 's [dat-polyfill](https://github.com/RangerMauve/dat-polyfill) and it might provide a simpler way of doing what I need, and would be easier to integrate here.

**Comment by RangerMauve** [comment]
Yeah, the Dat Polyfill is made exactly for this use case. :D Feel free to reach out if you want help setting it up.

**Comment by austinfrey** [comment]
@RangerMauve mind if I ping you on Gitter?

**Comment by RangerMauve** [comment]
Of course! I work 9-5 EST, but I can reply I'm between tasks
