### ISSUE TITLE
Access to Enoki Panel

### ISSUE THREAD

**Issue by laurent-d** [enokidotsite/enoki#3]
Hi @jondashkyle ,
Enoki looks great, i try it, but i have a question : How can i have access to panel ?
I have download the last Enoki starter kit  and install it, but when i run command npm start panel, the local url show me the site not the panel.
I'm doing something wrong ?
Many thanks.

**Comment by jondashkyle** [comment]
Hey @laurent-d, make sure you’re using the most recent release of the Starter-Kit which includes the `panel/` directory. Running `npm run panel` on the root directory should launch a new local server on port `8081`. Does navigating there display the panel?

**Comment by laurent-d** [comment]
Hi @jondashkyle,
I try port 8081 but it still display the main site, perhaps a cache issue, when I run npm start panel it display local host with 8080 port. Last detail I running on high sierra os.

`npm start panel
> enoki-starterkit@1.0.2 start /Users/laurentdelacerda/enoki-starterkit
> enoki dev "panel"
Server running on http://192.168.0.32:8080/
bundle - 1033256 bytes`

Do not hesitate for more details.

**Comment by laurent-d** [comment]
I download the last build it works thanks !

**Comment by jondashkyle** [comment]
Good to hear!
