### ISSUE TITLE
question: hasViewOrBlueprint()

### ISSUE THREAD

**Issue by jongacnik** [enokidotsite/enoki#4]
Curious whether we can get away without the has `hasViewOrBlueprint()` check in [lib/read/page.js#L56](https://github.com/jondashkyle/enoki/blob/master/lib/read/page.js#L56). I think it could make sense to simply make a rule of of 1 `.txt` file per directory — if it exists, use. It's just a thought, because otherwise it becomes a little more verbose to drop `enoki` into an app as purely a way to provide content. As it is now, the app needs to contain either a `blueprints` or a `views` directory, and there must be files within there which match the names of your `.txt` files in content. 

The ability to just have a content folder where you can put w/e and not have to think about filenames and blueprints etc I think would be a real nice way to use `enoki` on a lower level.

🍄🔥

**Edit:** I suppose this gets a little tricky if wanting to use `.txt` files for file meta data (like Kirby). Maybe the check becomes `hasMatchingFile()` or something? Just thoughts, the way it works now is perhaps still the best, esp if pushing people to use panel/specific app structure.

**Comment by jondashkyle** [comment]
Good one. One possible solutions is to use the existing `hasViewOrBlueprint()` method only if there are multiple `.txt` files which are not being used for file meta data. Alternatively, if there is a single `.txt` file in the directory, go ahead and use that.

**Comment by jongacnik** [comment]
Ya I think some checks like this is cool. I can put some thought around it and get a PR together if helpful!
